### PR TITLE
 #163281826 Adds an admin create meetup endpoint

### PR DESCRIPTION
**Pull request by Felix45**
**What does this pull request do**
- Adds a create meetup endpoint record to store in the database

**Description of the task to be completed**
- Add tests for creating meetup endpoint 
- Add endpoint for creating a meetup record

**How should this be manually tested**
- Clone or fork the repository 
`$ git clone https://github.com/Felix45/Questioner.git`

- Open a terminal and change the working directory to Questioner
`$ cd Questioner`

- Install a virtual environment
`$ virtualenv env`

- Once the environment is up, activate it using
`$ source env/bin/activate`

- Install all the requirements for the application using
`$ pip install -r requirements.txt`

- Checkout to branch ft-create-meetup-163281826
`$ git checkout ft-create-meetup-163281826`
- Enter the following commands into your terminal
```
$ export FLASK_APP=app
$ export FLASK_ENV=development 
$ export FLASK_DEBUG=1
flask run
```
Open a test client of your choice preferably postman and make the following requests, here I'm using postman
**Screen Shots**
```
POST http://127.0.0.1/api/v2/meetups
{
                    "location" : "Kileleshwa",
                    "images"   : ["survivor.png" , "well.jpg" , "healed.png"],
                    "topic"    : "Breast cancer Warriors",
                    "happeningOn" : "2019, 5, 17",
                    "Tags"         : ["women","mums","ladies"]
}
```
**Result**
create-meetup-3
create-meetup-db

```
POST http://127.0.0.1/api/v2/meetups
{
                    "location" : "",
                    "images"   : ["survivor.png" , "well.jpg" , "healed.png"],
                    "topic"    : "Breast cancer Warriors",
                    "happeningOn" : "2019, 5, 17",
                    "Tags"         : ["women","mums","ladies"]
}
```
**Result**
create-empty-meetup

```

### CODE REVIEW

**Comment by Siffersari** [comment]
Great job !

**Comment by KelynPNjeri** [comment]
Why do you have a token as an input

**Comment by Felix45** [comment]
> Why do you have a token as an input

Currently, I use the token to prevent users not logged In from posting meetups. I'm still looking for a way of sending tokens as part of headers.

**Comment by janetnim** [comment]
Why not pass token as headers?

**Comment by Felix45** [comment]
> Why not pass token as headers?

I'll implement that.

**Pull request merged**
